//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IronScraperMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialContentCurrent
    {
        public string Name { get; set; }
        public string Symbol { get; set; }
        public string Price { get; set; }
        public string PriceChange { get; set; }
        public string ChangePercent { get; set; }
        public string Volume { get; set; }
    }
}
